name: Android build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux -> Android-ARM32-ARM64

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform:     Android
        java-version: 8 # Override Java version

    - name: Build with Gradle
      if:   success()
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/Android
        chmod +x gradlew
        ./gradlew buildDebug
